version: "3.9"
services:
  api:
    build: .
    container_name: flynkle-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - minio
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flynkle
      POSTGRES_PASSWORD: flynkle
      POSTGRES_DB: flynkle
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
